treasurehunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('treasures.urls')),
]

treasures/urls.py
from django.urls import path
from . import views

app_name = 'treasures'
urlpatterns = [
    path('', views.homeindex.as_view(), name='home'),
    path('<int:val>/', views.detail, name='detail'),
    path('add/', views.add_new, name='new_treasure'),
    path('<int:val>/edit/', views.edit_treasure, name='edit_treasure'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

treasures/models.py
from django.db import models

# Create your models here.
class treasureGram(models.Model):
    name = models.CharField(max_length=50)
    value = models.DecimalField(max_digits=12, decimal_places=2)
    material = models.CharField(max_length=20)
    location = models.CharField(max_length=100)
    image_url = models.CharField(max_length=400)

    def __str__(self):
        return self.name

treasures/views.py
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import treasureGram
from .froms import treasureForm
from django.views import generic

# Create your views here.
class homeindex(generic.ListView):
    template_name = 'treasures/home.html'
    context_object_name = 'all_treasures'

    def get_queryset(self):
        return  treasureGram.objects.all()


def detail(request, val):
    treasure = treasureGram.objects.get(id =val)
    return render(request, 'treasures/detail.html', {'treasure': treasure})

def add_new(request):
    if request.method == 'POST':
        form = treasureForm(request.POST)
        if form.is_valid():
            treasure = form.save()
            treasure.save()
            return redirect('/')

    else:
        form = treasureForm()
        return render(request, 'treasures/new_treasure.html', {'form':form})

def edit_treasure(request, val):
    treasure = get_object_or_404(treasureGram, pk=val)
    if request.method=='POST':
        form = treasureForm(request.POST, instance=treasure)
        if form.is_valid():
            treasure = form.save()
            treasure.save()
            return redirect('treasures:detail', val=treasure.pk)
    else:
        form = treasureForm(instance=treasure)
        return render(request,'treasures/edit_treasure.html',{'form':form})


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email_id']
        password = request.POST['password']

        user = User.objects.create_user(username=username, first_name=firstname, last_name=lastname, email=email, password=password)
        user.save()
        print("user created")
        return redirect('/')

    else:
         return render(request, 'treasures/signup.html')


def login(request):
    if request.method == 'POST':
        username1 = request.POST['username']
        password1 = request.POST['password']
        from django.contrib import auth
        user = auth.authenticate(username=username1, password=password1)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            return HttpResponse('<h1 class="alert alert-success">incorrect password or username</h1>')

    else:
        return render(request,'treasures/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

treasures/templates/treasures/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'treasures/style.css' %}">

</head>
<body>
<nav style="background-color:gray" class="navbar-expand-sm navbar-light ">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
             <a class="nav-link" href="{% url 'treasures:home' %}">
                 <button type="button" class="btn btn-sm btn-outline-secondery">Homepage</button>
             </a>
        </li>
    </ul>
</nav>
     {% block content %}

     {% endblock %}

</body>
</html>

treasures/templates/treasures/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}

    <div class="container text-center">
        <h1>This is Our Detail Page</h1>
        <h1 class="alert alert-success">{{treasure.name}} </h1>
        <p>
           Value: {{treasure.value}}<br>
           Material: {{treasure.material}}<br>
           Location: {{treasure.location}}<br>
           <img src="{{treasure.image_url}}">
        </p>

    </div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/edit_treasure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h3 class="alert alert-success">Edit the treasure </h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
               <button type="submit">Save</button>
            </form>
    </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'treasures/style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
<nav style="background-color:gray" class="navbar-expand-sm navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarico">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarico">

       <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <a href="{% url 'treasures:logout' %}">
                     <button type="button" class="btn btn-sm btn-outline-secondery">logout</button>
                </a>
       </ul>
       <ul class="navbar-nav ml-auto">
                {% else %}
                <a href="{% url 'treasures:signup' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondery">Not_Regestered?signup</button>
                </a>

                <a href="{% url 'treasures:login' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondery">Regestered?login</button>
                </a>

       </ul>
           {% endif %}
    </div>
</nav>
<div class="album py-5 bg-light">
    <div style="...." class="container text-center">
       <h1  class="alert alert-success">this is homepage</h1>
        <div class="row">
          {% for treasure in all_treasures %}
            <div class="col-sm-4">
                <div class="card mb-4 box-shadow">
                     <img style="...." class="card-img-top" src="{{ treasure.image_url }}" alt="Treasure image">
                     <div class="card-body">
                          <h3>{{treasure.name}}</h3>
                       <div class="d-flex justify-content-between align-items-center">
                           <div class="btn-group">
                                 {% if user.is_authenticated %}
                                <a class="btn btn-primary" href="{% url 'treasures:detail' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">View</button>
                                </a>
                                <a class="btn btn-primary" href="{% url 'treasures:edit_treasure' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">Edit</button>
                                </a>
                                <a class="btn btn-primary" href="{% url 'treasures:new_treasure' %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondery">Add new</button>
                                </a>
                                  {% else %}
                                <a class="btn btn-primary" href="{% url 'treasures:detail' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">View</button>
                                </a>

                                   {% endif %}

                           </div>
                       </div>
                     </div>
                </div>
            </div>
          {% endfor %}
        </div>
    </div>
</div>


</body>
</html>

treasures/templates/treasures/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}

<div class="container text-center">
     <p>
        <h3 class="alert alert-success">Please put your correct username and password</h3>
        <form method="POST">
           {% csrf_token %}
           username:<input type="text" name="username">
           password:<input type="password" name="password">
           <input type="submit">
        </form>
     </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/new_treasure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h1 class="alert alert-success">Add New Treasures</h1>
        <form method="post" class="treasureForm" >
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-warning" type="submit">save</button>
        </form>
    </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h1 class="alert alert-success">Fillup this form</h1>
 <form  method="POST">
    {% csrf_token %}
    user name:<input type="text" name="username"><br>
    first name:<input type="text" name="firstname"><br>
    last name:<input type="text" name="lastname"><br>
    email id:<input type="email" name="email_id"><br>
    password:<input type="password" name="password"><br>
    <input type="submit">
 </form></p>
</div>
{% endblock %}
</body>
</html>